######################################################################
#
# File name : decoder_tb_wave.do
# Created on: Thu Oct 19 18:01:34 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
