######################################################################
#
# File name : decoder_tb_simulate.do
# Created on: Mon Oct 23 23:28:18 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.decoder_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {decoder_tb_wave.do}

view wave
view structure
view signals

do {decoder_tb.udo}

run 1000ns
