######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Thu Sep 21 14:35:13 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
