######################################################################
#
# File name : selector41_tb_wave.do
# Created on: Sat Oct 07 14:33:17 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
