######################################################################
#
# File name : selector41_simulate.do
# Created on: Sat Oct 07 14:31:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.selector41 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {selector41_wave.do}

view wave
view structure
view signals

do {selector41.udo}

run 1000ns
