######################################################################
#
# File name : selector41_wave.do
# Created on: Sat Oct 07 14:27:28 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
