######################################################################
#
# File name : selector41_tb_simulate.do
# Created on: Sat Oct 07 14:36:51 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.selector41_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {selector41_tb_wave.do}

view wave
view structure
view signals

do {selector41_tb.udo}

run 1000ns
