######################################################################
#
# File name : DataCompare4_tb_wave.do
# Created on: Thu Nov 02 13:30:00 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
