######################################################################
#
# File name : DataCompare4_tb_simulate.do
# Created on: Fri Nov 03 21:35:51 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.DataCompare4_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {DataCompare4_tb_wave.do}

view wave
view structure
view signals

do {DataCompare4_tb.udo}

run 1000ns
