set_property IOSTANDARD LVCMOS33 [get_ports oS]
set_property IOSTANDARD LVCMOS33 [get_ports oC]
set_property IOSTANDARD LVCMOS33 [get_ports iC]
set_property IOSTANDARD LVCMOS33 [get_ports iB]
set_property IOSTANDARD LVCMOS33 [get_ports iA]
set_property PACKAGE_PIN J15 [get_ports iA]
set_property PACKAGE_PIN L16 [get_ports iB]
set_property PACKAGE_PIN V10 [get_ports iC]
set_property PACKAGE_PIN K15 [get_ports oC]

set_property PACKAGE_PIN H17 [get_ports oS]
