######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Thu Sep 28 14:46:27 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
