######################################################################
#
# File name : DataCompare8_tb_wave.do
# Created on: Thu Nov 02 14:29:43 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
