######################################################################
#
# File name : tb_transmission8_simulate.do
# Created on: Sun Oct 08 12:58:15 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_transmission8 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_transmission8_wave.do}

view wave
view structure
view signals

do {tb_transmission8.udo}

run 1000ns
