######################################################################
#
# File name : tb_transmission8_wave.do
# Created on: Sun Oct 08 12:58:15 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
