######################################################################
#
# File name : transmission8_tb_wave.do
# Created on: Fri Oct 13 18:27:01 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
