######################################################################
#
# File name : transmission8_tb_simulate.do
# Created on: Fri Oct 13 19:39:43 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.transmission8_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {transmission8_tb_wave.do}

view wave
view structure
view signals

do {transmission8_tb.udo}

run 1000ns
