######################################################################
#
# File name : transmission8_tb_compile.do
# Created on: Fri Oct 13 19:39:40 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../transmission8.srcs/sources_1/new/transmission8.v" \
"../../../../transmission8.srcs/sources_1/new/transmission8_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

