######################################################################
#
# File name : encoder83_Pri_tb_wave.do
# Created on: Fri Oct 20 18:38:09 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
