######################################################################
#
# File name : tb_encoder83_Pri_wave.do
# Created on: Thu Oct 19 23:59:10 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
