######################################################################
#
# File name : tb_encoder83_Pri_compile.do
# Created on: Sat Oct 21 21:49:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
D:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../encoder83_Pri.srcs/sources_1/new/encoder83_Pri.v" \
"../../../../encoder83_Pri.srcs/sources_1/new/encoder83_Pri_tb.v" \


# compile glbl module
D:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

