######################################################################
#
# File name : game_tb_simulate.do
# Created on: Sat Jan 13 17:56:53 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L blk_mem_gen_v8_4_3 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.game_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {game_tb_wave.do}

view wave
view structure
view signals

do {game_tb.udo}

run 1000ns
