######################################################################
#
# File name : game_tb_compile.do
# Created on: Sat Jan 13 17:56:46 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/blk_mem_gen_v8_4_3

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap xpm modelsim_lib/msim/xpm
vmap blk_mem_gen_v8_4_3 modelsim_lib/msim/blk_mem_gen_v8_4_3

vlog -64 -incr -sv -work xil_defaultlib  \
"E:/NL/Vivado/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -64 -93 -work xpm  \
"E:/NL/Vivado/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -64 -incr -work blk_mem_gen_v8_4_3  \
"../../../../2048Diu.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../2048Diu.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../2048Diu.srcs/sources_1/new/BCDto8seg.v" \
"../../../../2048Diu.srcs/sources_1/new/Divider.v" \
"../../../../2048Diu.srcs/sources_1/new/MyMP3.v" \
"../../../../2048Diu.srcs/sources_1/new/clkdiv.v" \
"../../../../2048Diu.srcs/sources_1/new/gen.v" \
"../../../../2048Diu.srcs/sources_1/new/move.v" \
"../../../../2048Diu.srcs/sources_1/new/random.v" \
"../../../../2048Diu.srcs/sources_1/new/score.v" \
"../../../../2048Diu.srcs/sources_1/new/seg.v" \
"../../../../2048Diu.srcs/sources_1/new/shake.v" \
"../../../../2048Diu.srcs/sources_1/new/toBCD.v" \
"../../../../2048Diu.srcs/sources_1/new/top_game.v" \
"../../../../2048Diu.srcs/sources_1/new/vga.v" \
"../../../../2048Diu.srcs/sources_1/new/game_tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

