######################################################################
#
# File name : game_tb_wave.do
# Created on: Fri Jan 12 23:27:33 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
