######################################################################
#
# File name : encoder83_tb_wave.do
# Created on: Thu Oct 19 20:15:09 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
