######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Thu Sep 28 13:40:24 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
