######################################################################
#
# File name : Counter8_tb_compile.do
# Created on: Sat Nov 18 22:26:57 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
D:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../Counter8.srcs/sources_1/new/Counter8.v" \
"../../../../Counter8.srcs/sources_1/imports/new/Divider.v" \
"../../../../Counter8.srcs/sources_1/imports/homework/ex06/JK_FF/JK_FF.srcs/sources_1/new/JK_FF.v" \
"../../../../Counter8.srcs/sources_1/imports/homework/ex03/2/display7/display7.srcs/sources_1/new/display7.v" \
"../../../../Counter8.srcs/sources_1/new/Counter8_tb.v" \


# compile glbl module
D:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

