######################################################################
#
# File name : Counter8_tb_wave.do
# Created on: Sat Nov 18 22:25:44 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
