######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Tue Sep 26 14:01:06 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
