######################################################################
#
# File name : ram_tb_compile.do
# Created on: Thu Nov 23 17:34:03 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
D:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../ram.srcs/sources_1/new/ram_tb.v" \
"../../../../ram.srcs/sources_1/new/ram.v" \


# compile glbl module
D:\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

