######################################################################
#
# File name : ram_tb.udo
# Created on: Thu Nov 23 17:33:20 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
