set_property PACKAGE_PIN M17 [get_ports CLK]
set_property PACKAGE_PIN J15 [get_ports J]
set_property PACKAGE_PIN L16 [get_ports K]
set_property PACKAGE_PIN H17 [get_ports Q1]
set_property PACKAGE_PIN K15 [get_ports Q2]
set_property PACKAGE_PIN M18 [get_ports RST_n]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports J]
set_property IOSTANDARD LVCMOS33 [get_ports K]
set_property IOSTANDARD LVCMOS33 [get_ports Q1]
set_property IOSTANDARD LVCMOS33 [get_ports Q2]
set_property IOSTANDARD LVCMOS33 [get_ports RST_n]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK]

