######################################################################
#
# File name : extend_tb_simulate.do
# Created on: Sun Sep 24 11:10:21 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.extend_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {extend_tb_wave.do}

view wave
view structure
view signals

do {extend_tb.udo}

run 1000ns
