######################################################################
#
# File name : three_state_gates_tb.udo
# Created on: Sun Sep 24 10:31:50 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
