######################################################################
#
# File name : logic_gates_tb_wave.do
# Created on: Sun Sep 24 11:29:39 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
