######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Sun Sep 24 11:29:39 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
