######################################################################
#
# File name : logic_gates_tb.udo
# Created on: Thu Sep 21 13:51:41 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
